from decouple import config

APP_NAME=config('APP_NAME', default="My app")

OPENAI_BASE_URL=config('OPENAI_BASE_URL')
OPENAI_API_KEY=config('OPENAI_API_KEY')
OPENAI_ASSISTANT_VERSION=config('OPENAI_ASSISTANT_VERSION')
OPENAI_ASSISTANT_ID=config('OPENAI_ASSISTANT_ID')
OPENAI_BASE_MODEL=config('OPENAI_BASE_MODEL')
OPENAI_INSTRUCTIONS=config('OPENAI_INSTRUCTIONS')

OPENAI_DALLE_MODEL=config('OPENAI_DALLE_MODEL', default="dall-e-3")
OPENAI_DALLE_SIZE=config('OPENAI_DALLE_SIZE', default="1024x1024")